### ISSUE TITLE
TemplateNotFound error after building and running docker container (Windows 10)

### ISSUE THREAD

**Issue by gschennersie** [OpenReqEU/prs-improving-requirements-quality#3]
Hi,
After building and running the Docker container under Windows 10 accessing the service e.g. by
http://localhost:9799/index?requirementTitle=Requirement%20Title&requirementText=This%20is%20not%20a%20good%20requirement
leads to:
jinja2.exceptions.TemplateNotFound
jinja2.exceptions.TemplateNotFound: index.html

see stacktrace:
[stacktrace.txt](https://github.com/OpenReqEU/prs-improving-requirements-quality/files/3615158/stacktrace.txt)

KR Gottfried

**Comment by LloydThinks** [comment]
Hi @gschennersie,

After taking some time to review the error, it appears that there was a mistake in the code. In an attempt to make the build process quicker, I excluded the "demos" folder using .dockerignore settings. This made the demo inaccessible to the docker environment.

After enabling this again, however, it became apparent that this demo is not functional. Many development cycles has made this code outdated. However, the "csv - visualisation" demo serves the same purpose, and it allows input via CSV, which is much more usable than the url-based input of the "iframe" demo. Please use this demo (by opening the associated index.html file) to get a feel for the functionality of this microservice.

The original and intended usage of this microservice has also been functional throughout this mistake, so I hope you were able to utilise the service as is.

I have updated the README (https://github.com/OpenReqEU/prs-improving-requirements-quality/commit/c2425f16f356dbf27040535d6661a422842b2e06) to be more clear regarding the usage of the demos.

Lloyd
