### ISSUE TITLE
Help for dataset with annotation.

### ISSUE THREAD

**Issue by fangdequan1994** [OpenReqEU/prs-improving-requirements-quality#6]
Hello, Bro
I read your paper,  and I want to have a test with your dataset with annotation----the European Integrated Railway Radio Enhanced Network (EIRENE) [69] totalling 572 requirements.
Thanks a lot.
Good luck.

**Comment by LloydThinks** [comment]
Hello there,

How did you read my paper?

That dataset you are referring to is not my dataset. As referenced in the paper, it is a work by another researcher. Do you need help finding the direct link to the datset?

Lloyd

**Comment by fangdequan1994** [comment]
Thanks, Ur so kind!
I am now learning how to define regulations and accidentally find your paper in the web.That is beneficial for me. I donnot the principle to annotate the dataset though I read the iso-29148. So I cannot do the Second experiment. OK, I want that dataset.
Fang

**Comment by LloydThinks** [comment]
Where did you find my paper on the web? I would appreciate a link.

**Comment by fangdequan1994** [comment]
A Paper dataset. Now I cannot which one is because I browse 20+ dataset.

**Comment by LloydThinks** [comment]
That paper is not published, and as such should not be in the public domain.

**Comment by LloydThinks** [comment]
This is the dataset you are looking for: https://zenodo.org/record/1414117#.XrQMmRMzYUE

**Comment by fangdequan1994** [comment]
So sorry.Thank you very much.
